### ISSUE TITLE
RubyGemsにYAML.loadの挙動変更に対応したバージョンのgemを公開してほしい

### ISSUE THREAD

**Issue by furandon-pig** [yoshinari-nomura/mhc#64]
## 概要

 * RubyGemsに `mhc 1.2.5` のgemを公開してほしい。
 * Rubyの3系(3.1以降)から `YAML.load()` の挙動が変更されている。
   * 参考：[Ruby 3.1 で非互換になる YAML.load()](https://www.docswell.com/s/pink_bangbi/K67RV5-2022-01-06-201330)
 * mhcにおいては、[コミット1965818](https://github.com/yoshinari-nomura/mhc/commit/1965818653fd4789eb12fc5bcf5345c552547d59)で上記の挙動変更に対応している。
 * しかし、RubyGemで公開されている `mhc 1.2.4` のgemは上記の対応が入る前にリリースされたバージョンになっている。
 *  [コミット1965818](https://github.com/yoshinari-nomura/mhc/commit/1965818653fd4789eb12fc5bcf5345c552547d59)の内容を含んだ `mhc 1.2.5` をRubyGemsにリリースしてほしい。

## 再現手順

 * FreeBSD-13.2(amd64)環境では、以下の手順で問題を再現できます。

```sh
$ sudo pkg install ruby rubygem-gems git
$
$ # Rubyのバージョンは3.1でYAML.load()の挙動が変更されている。
$ ruby --version
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [amd64-freebsd13]
$
$ gem search -r mhc

*** REMOTE GEMS ***

mhc (1.2.4)
mhc-project-doc (1.0.2)
$
$ sudo gem install mhc -v 1.2.4
$ mhc init ~/mhc
$
$ # mhcのコマンド実行でエラーが発生する。
$ # (emacs向けmhcインタフェースでは"Wrong type argument: listp, /usr/local/lib/ruby/3\.1/psych\.rb:368:in"エラーが発生する)
$ mhc help
/usr/local/lib/ruby/3.1/psych.rb:368:in `load': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /usr/local/lib/ruby/gems/3.1/gems/mhc-1.2.4/lib/mhc/config.rb:55:in `create_from_yaml_string'
        from /usr/local/lib/ruby/gems/3.1/gems/mhc-1.2.4/lib/mhc/config.rb:51:in `create_from_yaml_file'
        from /usr/local/lib/ruby/gems/3.1/gems/mhc-1.2.4/lib/mhc/config.rb:214:in `create_from_file'
        from /usr/local/lib/ruby/gems/3.1/gems/mhc-1.2.4/bin/mhc:342:in `block in setup_global_options'
        from /usr/local/lib/ruby/gems/3.1/gems/mhc-1.2.4/bin/mhc:331:in `exit_on_error'
        from /usr/local/lib/ruby/gems/3.1/gems/mhc-1.2.4/bin/mhc:341:in `setup_global_options'
        from /usr/local/lib/ruby/gems/3.1/gems/mhc-1.2.4/bin/mhc:317:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.1/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1/gems/thor-1.3.0/lib/thor/base.rb:584:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/mhc-1.2.4/bin/mhc:388:in `<top (required)>'
        from /usr/local/bin/mhc:25:in `load'
        from /usr/local/bin/mhc:25:in `<main>'
```

## 発生要因

 * リポジトリの履歴を確認する。 `YAML.load()` の対応が入った[コミット1965818](https://github.com/yoshinari-nomura/mhc/commit/1965818653fd4789eb12fc5bcf5345c552547d59)よりも前に `1.24` のタグが打たれている。

```sh
$ git clone https://github.com/yoshinari-nomura/mhc.git
$ cd mhc
$ git blame lib/mhc/config.rb | grep ':unsafe_load'
19658186 (Yoshinari Nomura 2022-10-12 17:51:53 +0900  55)         hash = if YAML.respond_to?(:unsafe_load)
$ git log
...
commit 1965818653fd4789eb12fc5bcf5345c552547d59
Author: Yoshinari Nomura <nom@quickhack.net>
Date:   Wed Oct 12 17:51:53 2022 +0900

    Support YAML loader bundled with Ruby 3.1
...
commit 33d8ca1a1beb2b63e720e17525bdda3cc878e5ed (tag: v1.2.4)
Author: Yoshinari Nomura <nom@quickhack.net>
Date:   Fri Nov 13 09:01:54 2020 +0900

    Version 1.2.4
```

 * RubyGemには `mhc 1.2.5` のバージョンはまだ存在していない。

```sh
$ curl -sI https://rubygems.org/gems/mhc/versions/1.2.4 | head -n1
HTTP/2 200
$ curl -sI https://rubygems.org/gems/mhc/versions/1.2.5 | head -n1
HTTP/2 404
```

## 回避方法(workaround)

 * `lib/mhc/config.rb` に[コミット1965818](https://github.com/yoshinari-nomura/mhc/commit/1965818653fd4789eb12fc5bcf5345c552547d59)の修正内容をバックポートすることで、 `mhc 1.2.4` でも問題を回避することができる。

```sh
$ diff -u ../rubygem/lib/mhc/config.rb ./lib/mhc/config.rb
--- ../rubygem/lib/mhc/config.rb        2020-11-13 09:09:38.000000000 +0900
+++ ./lib/mhc/config.rb 2024-02-22 05:47:40.213281000 +0900
@@ -52,7 +52,11 @@
       end

       def self.create_from_yaml_string(yaml_string, filename = nil)
-        hash = YAML.load(yaml_string, filename) || {}
+        hash = if YAML.respond_to?(:unsafe_load)
+                 YAML.unsafe_load(yaml_string, filename: filename)
+               else
+                 YAML.load(yaml_string, filename)
+               end || {}
         return new(hash)
       end
```

**Comment by yoshinari-nomura** [comment]
Thanks. I've pushed 1.2.5 to rubyems.org.
  https://rubygems.org/gems/mhc/versions/1.2.5

**Comment by furandon-pig** [comment]
ご対応ありがとうございます。本件、closeいたします。
